language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc

branches:
  only:
    - master
    - develop

install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install python-catkin-pkg python-rosdep ros-hydro-catkin -qq
  - sudo rosdep init
  - rosdep update
  - mkdir -p /tmp/ws/src
  - ln -s `pwd` /tmp/ws/src/package
  - cd /tmp/ws
  - rosdep install --from-paths src --ignore-src --rosdistro hydro -y
  - sudo pip install ujson
before_script:
  - source /opt/ros/hydro/setup.bash
  - catkin_make
  - catkin_make install
  - sudo apt-get install ros-hydro-rostest
  - source devel/setup.bash
  - export ROS_MASTER_URI=http://localhost:11311
  - export ROS_HOSTNAME=localhost
script:
  - rostest rosbridge_library test_all.test
  - sudo pip uninstall ujson -y -q
  - rostest rosbridge_library test_all.test
