# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: hbpneurorobotics/nrp:dev

pipelines:
  branches:
    development:
    - step:
        name: Build
        size: 2x
        script:
          # Branch dependencies (ex-gerrit topic)
          - git archive --remote=ssh://git@bitbucket.org/hbpneurorobotics/admin-scripts.git refs/heads/master nrp_branch_topic_checkout | tar xf -
          - . ./nrp_branch_topic_checkout admin-scripts user-scripts ExperimentControl GazeboRosPackages
          - cd $BITBUCKET_CLONE_DIR

          # This plan depends on GazeboRosPackages being built
          - pushd $HBP/GazeboRosPackages && rm -rf build devel && catkin_make && popd && cd $BITBUCKET_CLONE_DIR
          
          # Checkout config.ini.sample from user-scripts
          - cp $HBP/user-scripts/config_files/CLE/config.ini.sample hbp_nrp_cle/hbp_nrp_cle/config.ini

          - git diff --diff-filter=ACMR --name-only HEAD^ # no idea what this does
          - export PYTHONPATH=hbp_nrp_cle:$PYTHONPATH

          # Concatenate all build requirements, ensure newline in between
          - (echo; cat $HBP/ExperimentControl/hbp_nrp_excontrol/requirements.txt) >> hbp_nrp_cle/requirements.txt

          # Configure build
          - export VIRTUAL_ENV=$VIRTUAL_ENV
          - export NRP_INSTALL_MODE=dev
          - export IGNORE_LINT='platform_venv|hbp_nrp_cle/hbp_nrp_cle/bibi_config/generated|hbp_nrp_cle/.eggs|nest'

          # python-tk is needed by matplotlib, which is needed by csa, which is required by spynnaker8
          # MPLBACKEND tells matplotlib not to use python-tk, so we can install spynnaker later without having python-tk
          - export MPLBACKEND=agg

          - virtualenv build_env && . build_env/bin/activate && pip install mock testfixtures matplotlib && make verify_base || { if [ -f pylint.txt ]; then echo "----------"; echo "PYLINT.TXT"; echo "----------";cat pylint.txt; fi; if [ -f pep8.txt ]; then echo "----------"; echo "PEP8.TXT"; echo "----------";cat pep8.txt; fi; exit 1; }

          # Coverage check
          - $HBP/admin-scripts/nrp_cobertura_check coverage.xml
