# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joint Position Controllers ---------------------------------------
# Head
robot_head_pan_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_ptu_pan_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_head_tilt_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_ptu_tilt_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

# Leg 0
robot_leg0_delta_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg0_delta_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg0_alpha_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg0_alpha_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg0_beta_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg0_beta_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg0_gamma_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg0_gamma_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

# Leg 1
robot_leg1_delta_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg1_delta_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg1_alpha_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg1_alpha_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg1_beta_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg1_beta_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg1_gamma_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg1_gamma_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

# Leg 2
robot_leg2_delta_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg2_delta_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg2_alpha_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg2_alpha_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg2_beta_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg2_beta_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg2_gamma_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg2_gamma_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

# Leg 3
robot_leg3_delta_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg3_delta_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg3_alpha_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg3_alpha_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg3_beta_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg3_beta_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg3_gamma_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg3_gamma_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

# Leg 4
robot_leg4_delta_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg4_delta_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg4_alpha_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg4_alpha_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg4_beta_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg4_beta_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg4_gamma_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg4_gamma_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

# Leg 5
robot_leg5_delta_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg5_delta_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg5_alpha_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg5_alpha_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg5_beta_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg5_beta_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}

robot_leg5_gamma_joint_pos_cntr:
  type: effort_controllers/JointPositionController
  joint: robot_leg5_gamma_joint
  pid: {p: 500.0, i: 0.01, d: 10.0}
